# Generated by Django 2.0.4 on 2018-04-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20180413_2308'),
        ('learning_logs', '0006_auto_20180413_1811'),
    ]

    operations = [
    ]
