# Generated by Django 2.0.3 on 2018-04-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageboard',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
    ]
