# Generated by Django 2.0.3 on 2018-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_auto_20180412_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='text',
            field=models.TextField(verbose_name='留言内容'),
        ),
    ]
