# Generated by Django 2.0.4 on 2018-04-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_auto_20180413_2053'),
        ('message_board', '0003_auto_20180415_1551'),
    ]

    operations = [
    ]
