# Generated by Django 2.0.3 on 2018-04-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.TextField(max_length='200', null=True),
        ),
    ]
