# Generated by Django 2.0.3 on 2018-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0003_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
