# Generated by Django 2.0.3 on 2018-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0004_auto_20180417_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '游戏名',
                'verbose_name_plural': '游戏名',
            },
        ),
    ]
